const data = [
  {
    "id": 1,
    "name_german": "Manni",
    "trivia_german": "Manni, das Mammut, liebt seine Freunde & Familie.",
    /* "trivia": "Manny is a mammoth who often protects his friends and is very strong.", */
    "group": "A",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 1,
    "name": "Manny",
    "max_weight": 6000,
    "max_age": 60,
    "top_speed": 25,
    "deaths": 0,
    "max_length": 450,
    "litter_size": 1,
    "continents": "North America, Eurasia",
    "intelligence": 6
  },
  {
    "id": 2,
    "name_german": "Ellie",
    "trivia_german": "Ellie ist ein humorvolles Mammut und die Partnerin von Manni.",
    "trivia": "Ellie is a female mammoth and Manny's partner.",
    "group": "A",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 2,
    "name": "Ellie",
    "max_weight": 5000,
    "max_age": 55,
    "top_speed": 20,
    "deaths": 0,
    "max_length": 420,
    "litter_size": 1,
    "continents": "North America, Eurasia",
    "intelligence": 6
  },
  {
    "id": 3,
    "name_german": "Peaches",
    "trivia_german": "Peaches, ein Mammut, ist die Tochter von Manni und Ellie.",
    "trivia": "Peaches is the daughter of Manny and Ellie.",
    "group": "A",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 3,
    "name": "Peaches",
    "max_weight": 3000,
    "max_age": 50,
    "top_speed": 20,
    "deaths": 0,
    "max_length": 380,
    "litter_size": 1,
    "continents": "North America, Eurasia",
    "intelligence": 6
  },
  {
    "id": 4,
    "name_german": "Julian",
    "trivia_german": "Julian, ein Mammut, ist Peaches' Partner und liebt Abenteuer.",
    "trivia": "Julian is Peaches' partner and loves adventure.",
    "group": "A",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 4,
    "name": "Julian",
    "max_weight": 3200,
    "max_age": 50,
    "top_speed": 22,
    "deaths": 0,
    "max_length": 370,
    "litter_size": 1,
    "continents": "North America, Eurasia",
    "intelligence": 6
  },
  {
    "id": 5,
    "name_german": "Diego",
    "trivia_german": "Diego ist ein schlauer und mutiger Säbelzahntiger und treuer Freund.",
    "trivia": "A saber-toothed tiger from the Ice Age movie series, known for his loyalty to his herd.",
    "group": "B",
    "groupname_german": "Raubtiere",
    "groupname": "Predators",
    "role": "Held",
    "group_number": 1,
    "name": "Diego",
    "max_weight": "400",
    "max_age": 20,
    "top_speed": 60,
    "deaths": 0,
    "max_length": 220,
    "litter_size": 3,
    "continents": "North America, South America",
    "intelligence": 12
  },
  {
    "id": 6,
    "name_german": "Shira",
    "trivia_german": "Shira ist ein Säbelzahntiger, die einen sehr eigenen Kopf hat.",
    "trivia": "Lived around 10,000 years ago and is famous for its long canines.",
    "group": "B",
    "groupname_german": "Raubtiere",
    "groupname": "Predators",
    "role": "Held",
    "group_number": 2,
    "name": "Shira",
    "max_weight": "350",
    "max_age": 20,
    "top_speed": 55,
    "deaths": 0,
    "max_length": 220,
    "litter_size": 3,
    "continents": "North America, South America",
    "intelligence": 10
  },
  {
    "id": 7,
    "name_german": "Sid",
    "trivia_german": "Sid ist das lustige und tollpatschige Faultier der Gruppe.",
    "trivia": "Sleeps up to 20 hours a day and moves very slowly",
    "group": "B",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 3,
    "name": "Sid",
    "max_weight": "6",
    "max_age": 30,
    "top_speed": 0.24,
    "deaths": 0,
    "max_length": 80,
    "litter_size": 1,
    "continents": "Americas",
    "intelligence": 3
  },
  {
    "id": 8,
    "name_german": "Brooke",
    "trivia_german": "Brooke, das Faultier, lebt in Geotopia und in Sid verliebt.",
    "trivia": "Sleeps up to 20 hours a day and moves very slowly",
    "group": "B",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 4,
    "name": "Brooke",
    "max_weight": "5",
    "max_age": 80,
    "top_speed": 0.24,
    "deaths": 0,
    "max_length": 80,
    "litter_size": 1,
    "continents": "Americas",
    "intelligence": 3
  },
  {
    "id": 9,
    "name_german": "Crash",
    "trivia_german": "Crash, das Opossum ist der Zwillingsbruder von Eddie und Adoptivbruder von Ellie.",
    "trivia": "Known for its tactic of playing dead.",
    "group": "C",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 1,
    "name": "Crash",
    "max_weight": "5",
    "max_age": 4,
    "top_speed": 7,
    "deaths": 0,
    "max_length": 55,
    "litter_size": 6,
    "continents": "Americas",
    "intelligence": 5
  },
  {
    "id": 10,
    "name_german": "Eddie",
    "trivia_german": "Eddie, das Opossum ist der Zwillingsbruder von Crash und Adoptivbruder von Ellie.",
    "trivia": "Known for its tactic of playing dead.",
    "group": "C",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 2,
    "name": "Eddie",
    "max_weight": "5",
    "max_age": 4,
    "top_speed": 7,
    "deaths": 0,
    "max_length": 55,
    "litter_size": 6,
    "continents": "Americas",
    "intelligence": 5
  },
  {
    "id": 11,
    "name_german": "Buck",
    "trivia_german": "Buckminster Wild ist ein Wiesel aus der Dinowelt und ein kleiner, flinker Räuber.",
    "trivia": "Small, agile predator.",
    "group": "C",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 3,
    "name": "Buck",
    "max_weight": "0.5",
    "max_age": 5,
    "top_speed": 25,
    "deaths": 0,
    "max_length": 20,
    "litter_size": 4,
    "continents": "Eurasia, Americas",
    "intelligence": 4
  },
  {
    "id": 12,
    "name_german": "Louis",
    "trivia_german": "Louis ist eine Maulwurfratte und ein guter Freund von Peaches.",
    "trivia": "Lives mostly underground.",
    "group": "C",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 4,
    "name": "Louis",
    "max_weight": "0.1",
    "max_age": 30,
    "top_speed": 5,
    "deaths": 0,
    "max_length": 15,
    "litter_size": 12,
    "continents": "Africa",
    "intelligence": 3
  },
  {
    "id": 13,
    "name_german": "Scrat",
    "trivia_german": "Scrat, ein Säbelzahn-Eichhörnchen verteitigt eine Eichel um sein Leben.",
    "trivia": "Hypothetical animal, known from pop culture.",
    "group": "D",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 1,
    "name": "Scrat",
    "max_weight": "0.8",
    "max_age": 10,
    "top_speed": 30,
    "deaths": 0,
    "max_length": 40,
    "litter_size": 2,
    "continents": "Unknown",
    "intelligence": 4
  },
  {
    "id": 14,
    "name_german": "Oma",
    "trivia_german": "Gladys, meist Oma genannt, ist die Großmutter von Sid.",
    "trivia": "Famous for its slow movement.",
    "group": "D",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Held",
    "group_number": 2,
    "name": "Oma",
    "max_weight": "6",
    "max_age": 20,
    "top_speed": 0.2,
    "deaths": 0,
    "max_length": 75,
    "litter_size": 1,
    "continents": "Americas",
    "intelligence": 3
  },
  {
    "id": 15,
    "name_german": "Shangri Llama",
    "trivia_german": "Shangri Llama, ein Llama ist Führer von Geotopia und ist über 400 Jahre alt",
    "trivia": "Often used as a pack animal in the Andes.",
    "group": "D",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 3,
    "name": "Shangri Llama",
    "max_weight": "200",
    "max_age": 400,
    "top_speed": 40,
    "deaths": 0,
    "max_length": 120,
    "litter_size": 1,
    "continents": "South America",
    "intelligence": 5
  },
  {
    "id": 16,
    "name_german": "Teddy",
    "trivia_german": "Teddy, ein Palaeolagus ist ein Schüler von Shangri Llama und verliebt in Oma.",
    "trivia": "An extinct relative of today's rabbit.",
    "group": "D",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 4,
    "name": "Teddy",
    "max_weight": "1.2",
    "max_age": 8,
    "top_speed": 15,
    "deaths": 0,
    "max_length": 30,
    "litter_size": 3,
    "continents": "North America",
    "intelligence": 3
  },
  {
    "id": 1,
    "name_german": "Captain Utan",
    "trivia_german": "Captain Utan, ein Gigantopithecus ist der Anführer der Piratenbande.",
    "trivia": "An extinct giant ape that lived around 100,000 years ago.",
    "group": "E",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Schurke",
    "group_number": 1,
    "name": "Captain Utan",
    "max_weight": "500",
    "max_age": 35,
    "top_speed": 8,
    "deaths": "unknown",
    "max_length": 300,
    "litter_size": 1,
    "continents": "Asia",
    "intelligence": 5
  },
  {
    "id": 2,
    "name_german": "Flynn",
    "trivia_german": "Flynn ist ein See-Elefant und ein Mitglied in Captain Utans Crew.",
    "trivia": "The largest member of the seal family, weighing over 2 tons.",
    "group": "E",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Schurke",
    "group_number": 2,
    "name": "Flynn",
    "max_weight": "4000",
    "max_age": 20,
    "top_speed": 8,
    "deaths": "unknown",
    "max_length": 600,
    "litter_size": 1,
    "continents": "Antarctica, South America",
    "intelligence": 3
  },
  {
    "id": 3,
    "name_german": "Squint",
    "trivia_german": "Squint ist ein Kaninchen und Mitglied von Captain Utans Crew.",
    "trivia": "Known for its high reproduction rate.",
    "group": "E",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Schurke",
    "group_number": 3,
    "name": "Squint",
    "max_weight": "2",
    "max_age": 12,
    "top_speed": 35,
    "deaths": "unknown",
    "max_length": 50,
    "litter_size": 12,
    "continents": "All continents except Antarctica",
    "intelligence": 2
  },
  {
    "id": 4,
    "name_german": "Raz",
    "trivia_german": "Raz ist ein Mitglied in Captain Utans Crew und die Waffenexpertin.",
    "trivia": "Known for its jumping ability and pouch for its young.",
    "group": "E",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Schurke",
    "group_number": 4,
    "name": "Raz",
    "max_weight": "90",
    "max_age": 23,
    "top_speed": 70,
    "deaths": "unknown",
    "max_length": 250,
    "litter_size": 1,
    "continents": "Australia",
    "intelligence": 4
  },
  {
    "id": 5,
    "name_german": "Silas",
    "trivia_german": "Silas, ein Blaufußtölpel-Hybrid ist ein treues Mitglied der Piratencrew von Utan",
    "trivia": "Known for its blue feet and courtship dances.",
    "group": "F",
    "groupname_german": "Vögel",
    "groupname": "Birds",
    "role": "Schurke",
    "group_number": 1,
    "name": "Silas",
    "max_weight": "1.5",
    "max_age": 17,
    "top_speed": 40,
    "deaths": "unknown",
    "max_length": 90,
    "litter_size": 3,
    "continents": "Americas",
    "intelligence": 3
  },
  {
    "id": 6,
    "name_german": "Gupta",
    "trivia_german": "Gupta ist ein Dachs und ein Mitglied von Captain Utans Crew.",
    "trivia": "Notorious for its aggressive defense instinct.",
    "group": "F",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Schurke",
    "group_number": 2,
    "name": "Gupta",
    "max_weight": "14",
    "max_age": 16,
    "top_speed": 30,
    "deaths": "unknown",
    "max_length": 85,
    "litter_size": 5,
    "continents": "Europe, Asia, Americas",
    "intelligence": 3
  },
  {
    "id": 7,
    "name_german": "Dobson",
    "trivia_german": "Dobson ist ein Wildschwein und ein Mitglied von Captain Utans Crew.",
    "trivia": "Ancestor of many domestic pig breeds.",
    "group": "F",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Schurke",
    "group_number": 3,
    "name": "Dobson",
    "max_weight": "150",
    "max_age": 15,
    "top_speed": 40,
    "deaths": "unknown",
    "max_length": 180,
    "litter_size": 6,
    "continents": "Europe, Asia, Africa",
    "intelligence": 4
  },
  {
    "id": 8,
    "name_german": "Scratte",
    "trivia_german": "Scratte, ein Säbelzahn-Eichhörnchen, die zwar süß ist, aber auch gierig.",
    "trivia": "Known from myths and pop culture, possibly an ancestor of modern rodents.",
    "group": "F",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 4,
    "name": "Scrattie",
    "max_weight": "0.5",
    "max_age": 8,
    "top_speed": 15,
    "deaths": "unknown",
    "max_length": 60,
    "litter_size": 3,
    "continents": "North America",
    "intelligence": 3
  },
  {
    "id": 6,
    "name_german": "Ethan",
    "trivia_german": "Ethan ist ein Mammut, Peaches' Schwarm und Anführer einer Clique.",
    "trivia": "Once roamed the icy plains, extinct for around 4,000 years.",
    "group": "G",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 1,
    "name": "Ethan",
    "max_weight": "8000",
    "max_age": 60,
    "top_speed": 25,
    "deaths": 0,
    "max_length": 450,
    "litter_size": 1,
    "continents": "Eurasia, North America",
    "intelligence": 4
  },
  {
    "id": 6,
    "name_german": "Steffie",
    "trivia_german": "Steffie ist ein Mammut und gehört zu der Clique von Ethan, Meghan und Katie.",
    "trivia": "Once roamed the icy plains, extinct for around 4,000 years.",
    "group": "G",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 2,
    "name": "Steffie",
    "max_weight": "8000",
    "max_age": 60,
    "top_speed": 25,
    "deaths": 0,
    "max_length": 450,
    "litter_size": 1,
    "continents": "Eurasia, North America",
    "intelligence": 4
  }, {
    "id": 6,
    "name_german": "Katie",
    "trivia_german": "Katie, ein Mammut, die mit zur Clique gehört und wegen ihrer Haarfarbe bewundert wird.",
    "trivia": "Once roamed the icy plains, extinct for around 4,000 years.",
    "group": "G",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 3,
    "name": "Katie",
    "max_weight": "8000",
    "max_age": 60,
    "top_speed": 25,
    "deaths": 0,
    "max_length": 450,
    "litter_size": 1,
    "continents": "Eurasia, North America",
    "intelligence": 4
  }, {
    "id": 6,
    "name_german": "Meghan",
    "trivia_german": "Meghan, ein Mammut, welches sehr eingebildet ist und zur Clique gehört.",
    "trivia": "Once roamed the icy plains, extinct for around 4,000 years.",
    "group": "G",
    "groupname_german": "Säugetiere",
    "groupname": "Mammals",
    "role": "Sidekick",
    "group_number": 4,
    "name": "Meghan",
    "max_weight": "8000",
    "max_age": 60,
    "top_speed": 25,
    "deaths": 0,
    "max_length": 450,
    "litter_size": 1,
    "continents": "Eurasia, North America",
    "intelligence": 4
  },
  {
    "id": 7,
    "name_german": "Gavin",
    "trivia_german": "Gavin ist ein Dakotaraptor und Anführer einer Gruppe von Flugsauriern.",
    "trivia": "A bird-like predatory dinosaur from the Cretaceous period.",
    "group": "H",
    "groupname_german": "Dinosaurier",
    "groupname": "Dinosaurs",
    "role": "Schurke",
    "group_number": 1,
    "name": "Gavin",
    "max_weight": "300",
    "max_age": 15,
    "top_speed": 50,
    "deaths": 0,
    "max_length": 500,
    "litter_size": 5,
    "continents": "North America",
    "intelligence": 3
  },
  {
    "id": 7,
    "name_german": "Gertie",
    "trivia_german": "Gertie ein Dakotaraptor, ist die Tochter von Gavin und ältere Schwester von Roger.",
    "trivia": "A bird-like predatory dinosaur from the Cretaceous period.",
    "group": "H",
    "groupname_german": "Dinosaurier",
    "groupname": "Dinosaurs",
    "role": "Schurke",
    "group_number": 2,
    "name": "Gertie",
    "max_weight": "300",
    "max_age": 15,
    "top_speed": 50,
    "deaths": 0,
    "max_length": 500,
    "litter_size": 5,
    "continents": "North America",
    "intelligence": 3
  }, {
    "id": 7,
    "name_german": "Roger",
    "trivia_german": "Roger ein Dakotaraptor, ist der Sohn von Gavin und kleine Bruder von Gertie.",
    "trivia": "A bird-like predatory dinosaur from the Cretaceous period.",
    "group": "H",
    "groupname_german": "Dinosaurier",
    "groupname": "Dinosaurs",
    "role": "Schurke",
    "group_number": 3,
    "name": "Roger",
    "max_weight": "300",
    "max_age": 15,
    "top_speed": 50,
    "deaths": 0,
    "max_length": 500,
    "litter_size": 5,
    "continents": "North America",
    "intelligence": 3
  },
  {
    "id": 8,
    "name_german": "Soto",
    "trivia_german": "Soto, ein Säbelzahntiger und Anführer eines Rudels, zu dem Diego mal gehörte.",
    "trivia": "An iconic predator of the last Ice Age, famous for its long canines.",
    "group": "H",
    "groupname_german": "Raubtiere",
    "groupname": "Predators",
    "role": "Schurke",
    "group_number": 4,
    "name": "Soto",
    "max_weight": "400",
    "max_age": 25,
    "top_speed": 48,
    "deaths": 0,
    "max_length": 250,
    "litter_size": 3,
    "continents": "North and South America",
    "intelligence": 3
  },
]